#!/usr/bin/env zsh

alias vim='$VIM'
alias vi='$VIM'

alias t="tmux a"
alias c="clear"
alias p="cd ~/projects/"
alias f="fuck"
alias s=server

alias msync="rsync -rvaE --progress --delete"

alias ls='ls --color '
alias l='ls -lh '   
alias la='ls -lAh '

alias icat='kitty icat '

