#!/usr/bin/env zsh

alias vim='$VIM'
alias vi='$VIM'
alias v='$VIM'

alias msync="rsync -rvaE --progress --delete"

alias ls='ls --color '
alias l='ls -lh '   
alias la='ls -lAh '

alias icat='kitty icat '
alias switchos='~/.config/personal/scripts/switch-os'
alias start-docker='sudo systemctl start docker'
alias stop-docker='sudo systemctl stop docker'
alias tmux-sessionizer='~/.config/personal/scripts/tmux-sessionizer'
alias vpn='sudo vpn'

alias t="tmux attach || ~/.config/personal/scripts/tmux-sessionizer"
alias c="clear"
alias p="cd ~/projects/"
alias f="fuck"
alias s=server
alias d=sway
alias e='$EDITOR'

alias what-playing='xdg-open "https://www.google.com/search?q=$(playerctl metadata --format '\''{{artist}} {{album}}'\'' | sed '\''s/ /+/g'\'')"'

alias jetbrains-toolbox='SKIKO_RENDER_API=DIRECT_SOFTWARE jetbrains-toolbox'
