#!/usr/bin/env bash

addToPath() {
    if [[ "$PATH" != *"$1"* ]]; then
        export PATH=$PATH:$1
    fi
}

addToPathFront() {
    if [[ "$PATH" != *"$1"* ]]; then
        export PATH=$1:$PATH
    fi
}

# Edit dotfiles config
conf() {
    target=$( (find "$XDG_CONFIG_HOME" -type f ; find "$HOME" -maxdepth 1 -type f) | fzf)
    if [ -n "$target" ]
    then
        $VIM "$target" 
    fi
}

# Connect ssh server from given list
server() {
    if [ -z "$PRIVATE_SSH_SERVERS_PATH" ]; then
        echo "Error: PRIVATE_SSH_SERVERS_PATH is not set";
        return 1;
    fi
    selected_server=$(fzf --height 20% --layout=reverse --border < "$PRIVATE_SSH_SERVERS_PATH")
    if [ -n "$selected_server" ]; then
        ssh "$selected_server"
    fi
}

# Stands for Fuzzy find vIM 
fim() {
    selected_file=$(find . -type f -not -path '*/\.*' | fzf)
    if [ -n "$selected_file" ]; then
        $VIM "$selected_file"
    fi
}

