#!/usr/bin/env zsh

bindkey -e # emacs keybinds if i need ^A, ^E, etc

bindkey -v # vi keybinds
bindkey "^H" backward-delete-char # fix backspace after vi keybinds
bindkey "^?" backward-delete-char # fix backspace after vi keybinds

bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
bindkey '^y' autosuggest-accept
bindkey -s "^o" "cd ..\n"
bindkey -s "^f" "^u$XDG_CONFIG_HOME/personal/scripts/tmux-sessionizer^M"
