tap "armmbed/formulae"
tap "getsentry/tools"
tap "homebrew/bundle"
tap "homebrew/services"
tap "peripheryapp/periphery"

brew "sl"
brew "cmatrix"
brew "cowsay"
brew "thefuck"

brew "stow"
brew "fd"
brew "fzf"
brew "grep"
brew "grep"
brew "ripgrep"
brew "bash-language-server"
brew "neovim"
brew "tmux"
brew "tldr"
brew "tree"
brew "zsh-autosuggestions"

brew "go"
brew "pkl"
brew "luarocks"

brew "ffmpeg"
brew "imagemagick"
brew "pkg-config"
brew "speedtest-cli"
brew "yt-dlp"

brew "swiftlint"
brew "getsentry/tools/sentry-cli"

cask "appcleaner"
cask "discord"
cask "google-chrome"
cask "iina"
cask "kitty"
cask "outline-manager"
cask "periphery"
cask "shadowsocksx-ng"
cask "transmission"
cask "vlc"
cask "zoom"

