stream.rules = [
  {
    matches = [
      { application.process.binary = "firefox" }
      { application.name = "PipeWire ALSA [firefox]" }
    ]
    actions = { update-props = { resample.disable = true, channelmix.disable = true } }
  }
]
