stream.rules = [
  {
    matches = [
      { application.process.binary = "qbz" }
      { application.name = "PipeWire ALSA [qbz]" }
    ]
    actions = { update-props = { resample.disable = true, channelmix.disable = true } }
  }
  {
    matches = [
      { application.process.binary = "vlc" }
      { application.name = "PipeWire ALSA [vlc]" }
    ]
    actions = { update-props = { resample.disable = true, channelmix.disable = true } }
  }
  {
    matches = [
      { application.process.binary = "deadbeef" }
      { application.name = "PipeWire ALSA [deadbeef]" }
    ]
    actions = { update-props = { resample.disable = true, channelmix.disable = true } }
  }
  {
    matches = [
      { application.process.binary = "strawberry" }
      { application.name = "PipeWire ALSA [strawberry]" }
    ]
    actions = { update-props = { resample.disable = true, channelmix.disable = true } }
  }
  {
    matches = [
      { application.process.binary = "clementine" }
      { application.name = "PipeWire ALSA [clementine]" }
    ]
    actions = { update-props = { resample.disable = true, channelmix.disable = true } }
  }
  {
    matches = [
      { application.process.binary = "qobuz-player" }
      { application.name = "PipeWire ALSA [qobuz-player]" }
    ]
    actions = { update-props = { resample.disable = true, channelmix.disable = true } }
  }
  {
    matches = [
      { application.process.binary = "subtui" }
      { application.name = "PipeWire ALSA [subtui]" }
    ]
    actions = { update-props = { resample.disable = true, channelmix.disable = true } }
  }
  {
    matches = [
      { application.process.binary = "firefox" }
      { application.name = "PipeWire ALSA [firefox]" }
    ]
    actions = { update-props = { resample.disable = true, channelmix.disable = true } }
  }
]
