#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo 'Switching to Mac OS...';
    sudo asahi-bless --set-boot-macos -y && sudo reboot;
elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo 'Switching to Asahi...';
    sudo bless --mount "/Volumes/asahi" --setBoot && sudo reboot;
else
    echo "Error: Unsupported platform $OSTYPE";
    exit 1;
fi

