#!/usr/bin/env zsh

alias vim='$VIM'
alias vi='$VIM'

alias t="tmux a"
alias c="clear"
alias p="cd ~/projects/"
alias ssh="kitten ssh "
alias f="fuck"
alias s=server

alias msync="rsync -rvaE --progress --delete"

alias ls='ls --color '
alias l='ls -lFh '   
alias la='ls -lAFh '
alias ll='ls -l '

