monitor.alsa.rules = [
  {
    matches = [
      { node.name = "alsa_output.usb-OPPO_OPPO_HA-1_USB_AUDIO_2.0_DAC-00.pro-output-0", media.class = "Audio/Sink" }
    ]
    actions = {
      update-props = {
        audio.allowed-rates = [ 44100 48000 88200 96000 176400 192000 ]
        resample.disable = true
        channelmix.disable = true
      }
    }
  }
]
