# OHMYZSH CONFIGURATION
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

export ZSH="$HOME/.oh-my-zsh"

# Theme for oh-my-zsh
function git_branch_name()
{
  branch=$(git symbolic-ref HEAD 2> /dev/null | awk 'BEGIN{FS="/"} {print $NF}')
  if [[ $branch == "" ]];
  then
    :
  else
      if [ $(git status --porcelain | wc -l) -eq "0" ]; then
        echo ' ('$branch')'
      else
        echo " (%{$fg[red]%}$branch%{$reset_color%})"
      fi
  fi
}
PROMPT='%{$fg[cyan]%}%1/%{$reset_color%}$(git_branch_name) %% '

# '_' and '-' are the same in completion
HYPHEN_INSENSITIVE="true"

# update automatically without asking
zstyle ':omz:update' mode auto

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS="true"

ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"

plugins=(git)

source $ZSH/oh-my-zsh.sh



# User configuration

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

export XDG_CONFIG_HOME=$HOME/.config
VIM="nvim"

PERSONAL=$XDG_CONFIG_HOME/personal
source $PERSONAL/env
for i in `find -L $PERSONAL`; do
    source $i
done

eval "$(fzf --zsh)"

export GIT_EDITOR=$VIM
export GOPATH=$HOME/go

addToPathFront $HOME/go/bin

setupConda() {
	# >>> conda initialize >>>
	# !! Contents within this block are managed by 'conda init' !!
	__conda_setup="$('/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
	if [ $? -eq 0 ]; then
	    eval "$__conda_setup"
	else
	    if [ -f "/opt/anaconda3/etc/profile.d/conda.sh" ]; then
		. "/opt/anaconda3/etc/profile.d/conda.sh"
	    else
		export PATH="/opt/anaconda3/bin:$PATH"
	    fi
	fi
	unset __conda_setup
	# <<< conda initialize <<<
}

setupConda

export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
export PATH="/opt/homebrew/opt/gradle@6/bin:$PATH"
alias ramus='cd ~/src/ramus/ && gradle runLocal &'
eval $(thefuck --alias)

## [Completion]
## Completion scripts setup. Remove the following line to uninstall
[[ -f /Users/tikhon/.config/.dart-cli-completion/zsh-config.zsh ]] && . /Users/tikhon/.config/.dart-cli-completion/zsh-config.zsh || true
## [/Completion]


export STM32CubeMX_PATH=/Applications/STMicroelectronics/STM32CubeMX.app/Contents/Resources

export STM32_PRG_PATH=/Applications/STMicroelectronics/STM32Cube/STM32CubeProgrammer/STM32CubeProgrammer.app/Contents/MacOs/bin

